# .github/workflows/node-ci.yml

# Name of your workflow
name: Node.js CI Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all branches
  push:
  
  # Triggers the workflow on pull request events for all branches
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is named "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository so the job can access your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up the Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a stable LTS version of Node.js
          cache: 'npm'       # Caches npm packages for faster builds

      # 3. Installs dependencies (good practice, even if we only have dev dependencies)
      - name: Install dependencies
        run: npm install

      # 4. Runs the test script defined in package.json
      - name: Run tests
        run: npm test
